apiVersion: v1
kind: Service
metadata:
  name: nid-backend-service
  namespace: nid
  labels:
    app: nid-backend
spec:
  type: NodePort
  selector:
    app: nid-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000