apiVersion: v1
kind: Service
metadata:
  name: nid-frontend-service
  namespace: nid
  labels:
    app: nid-frontend
spec:
  type: NodePort
  selector:
    app: nid-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001