apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: nid-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80              # ingress HTTP
        protocol: TCP
      - containerPort: 443
        hostPort: 443             # ingress HTTPS 
        protocol: TCP
      - containerPort: 30000
        hostPort: 8000            # NodePort backend
        protocol: TCP
      - containerPort: 30001
        hostPort: 8501            # NodePort frontend  
        protocol: TCP

  - role: worker
    labels:
      node-type: worker

  - role: worker
    labels:
      node-type: worker